[package]
name = "megascope"
version = "0.1.0"
edition = "2021"

[dependencies]
avian2d = "0.2.1"
rand = "0.9.0"

[dependencies.bevy]
version = "0.15.3"
features = ["animation", "bevy_asset", "bevy_audio", "bevy_color", "bevy_core_pipeline", "bevy_gilrs", "bevy_gizmos", "bevy_gltf", "bevy_mesh_picking_backend", "bevy_pbr", "bevy_picking", "bevy_render", "bevy_scene", "bevy_sprite", "bevy_sprite_picking_backend", "bevy_state", "bevy_text", "bevy_ui", "bevy_ui_picking_backend", "bevy_window", "bevy_winit", "custom_cursor", "default_font", "hdr", "multi_threaded", "png", "smaa_luts", "sysinfo_plugin", "tonemapping_luts", "vorbis", "webgl2", "wayland", "bevy_dev_tools"]
default-features = false

# Enable a small amount of optimization in the dev profile.
[profile.dev]
opt-level = 1

# Enable a large amount of optimization in the dev profile for dependencies.
[profile.dev.package."*"]
opt-level = 3
