name: Build WASM Example

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          rustflags:

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true

      - name: Add wasm32 target
        run: rustup target add wasm32-unknown-unknown

      - name: Install wasm-bindgen-cli
        run: cargo install wasm-bindgen-cli

      - name: Build with cargo
        run: cargo build --release --target wasm32-unknown-unknown

      - name: Run wasm-bindgen
        run: |
          wasm-bindgen --out-dir examples/wasm/target \
                       --out-name wasm_example \
                       --target web target/wasm32-unknown-unknown/release/*.wasm

      - name: Upload artifact (optional)
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          name: wasm-example
          path: examples/wasm

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4